### PR TITLE
Add prefecture_code into addresses_array map

### PR DESCRIPTION
**Pull request by pione30**
It might be useful `addresses_array` having a prefecture code :)
(Say, for automatically selecting `<select>` tag from user's zip code input)

### CODE REVIEW

**Comment by pione30** [comment]
When https://github.com/rinkei/jipcode/pull/6 is merged I'll rebase this branch on it :)

**Comment by pione30** [comment]
@rinkei Thanks for merging https://github.com/rinkei/jipcode/pull/6 !
Now CI gets to pass, could you also review this PR?

**Comment by rinkei** [comment]
@pione30 I think jipcode basicaly should have only elements that is contained in KEN_ALL.CSV. It has been already fit most usecases.

Your suggestion will make jipcode more useful.
But following above policy I want extending output to be optional.

for example, like this
```ruby
  PREFECTURE_CODE = YAML.load_file("#{File.dirname(__FILE__)}/../prefecture_code.yml").freeze

  def locate(zipcode, opt={})
    # 数字7桁以外の入力は受け付けない
    return [] unless zipcode =~ /\A\d{7}?\z/

    # 上3桁にマッチするファイルが存在しなければ該当なし
    path = "#{ZIPCODE_PATH}/#{zipcode[0..2]}.csv"
    return [] unless File.exist?(path)

    addresses_array = CSV.read(path).select { |address_row| address_row[0] == zipcode }

    if opt.empty?
      addresses_array.map { |address_param| basic_address_from(address_param) }
    else
      addresses_array.map { |address_param| extended_address_from(address_param, opt) }
    end
  end

  def basic_address_from(address_param)
    {
      zipcode:    address_param[0],
      prefecture: address_param[1],
      city:       address_param[2],
      town:       address_param[3]
    }
  end

  def extended_address_from(address_param, opt={})
    address = basic_address_from(address_param)
    address[:prefecture_code] = PREFECTURE_CODE.invert[address_param[1]] if opt[:prefecture_code]
    address
  end

  module_function :locate, :basic_address_from, :extended_address_from
```

**Comment by pione30** [comment]
@rinkei 

> But following above policy I want extending output to be optional.

I understood :+1: 

Since `extended_address_from` with empty `opt` returns the same hash as `basic_address_from`, there's no need to branch the condition:

```ruby
if opt.empty?
  # ...
else
  # ...
end
```

and just calling

```ruby
addresses_array.map { |address_param| extended_address_from(address_param, opt) }
```

is enough? :)

**Comment by rinkei** [comment]
@pione30 The conditional branch avoids multiple `if opt[:prefecture_code]` in `#exteded_address_from`.
`addresses_array.map` calls the method multiple time.

I want the default behavior (no options) to move as quickly as possible.

**Comment by pione30** [comment]
@rinkei OK I've fixed the code :)

**Comment by rinkei** [comment]
@pione30 I merged & released this PR. This is going to makes jipcode more useful.😊
Thank you for your cooperation!

**Pull request merged**
